package agent

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// AgentsMDStub is what `init` writes when the project has no AGENTS.md,
// and what the SPEC-013 migration puts where the generated header was.
// After that the file belongs to the user. The last sentence is for
// fresh clones and cloud agents that never ran sync.
const AgentsMDStub = "# AGENTS.md\n\n" +
	"Shared rules, skills, and workflows for this project live in `.agents/`.\n" +
	"`sync-agents sync` delivers them to each tool's native location. If your tool\n" +
	"has not loaded them, read the files in `.agents/rules/` that apply to your task.\n"

// agentsMDBackupRel is where the pre-migration AGENTS.md is kept,
// relative to the project's .agents/. It is written once, before the
// first migration rewrite, and never overwritten, so the migration can
// always be undone by hand.
const agentsMDBackupRel = ".sync/AGENTS.md.pre-spec013"

// legacyClaudeImportsRegion is the @-import block SPEC-013 retires.
// Claude Code loads .claude/rules/*.md and ~/.claude/rules/*.md on its
// own, so the block only duplicated (and drifted from) that set. It is
// kept solely so the migration can strip it from AGENTS.md and global
// sync can strip it from ~/.claude/CLAUDE.md.
var legacyClaudeImportsRegion = ManagedRegion{Name: "claude-imports"}

// AgentsMDMigration reports what migrateAgentsMD changed.
type AgentsMDMigration struct {
	Header        bool     // the generated header was replaced by AgentsMDStub
	Removed       []string // generated sections removed: "Rules", "Skills", ...
	Kept          []string // generated titles kept because they hold hand-written lines
	ClaudeImports bool     // the claude-imports region was removed
}

// Changed reports whether migration rewrote anything.
func (m AgentsMDMigration) Changed() bool {
	return m.Header || m.ClaudeImports
}

// summary renders m as one human-readable clause list for the log.
func (m AgentsMDMigration) summary() string {
	var parts []string
	if m.Header {
		parts = append(parts, "replaced the generated header with a short pointer to .agents/")
	}
	if len(m.Removed) > 0 {
		parts = append(parts, "removed "+strings.Join(m.Removed, ", "))
	}
	if m.ClaudeImports {
		parts = append(parts, "removed the claude-imports block")
	}
	if len(m.Kept) > 0 {
		parts = append(parts, "kept "+strings.Join(m.Kept, ", ")+" (hand-written lines)")
	}
	return strings.Join(parts, "; ")
}

// generatedHeader is the header every earlier generator wrote, from
// bash 0.1 through Go 1.10. It is compared line by line, skipping blank
// lines (the bash generator wrote a leading blank line). Only a file
// that starts with it is provably generated, and sections are stripped
// only from such a file.
var generatedHeader = []string{
	"---",
	"trigger: always_on",
	"---",
	"# AGENTS",
	"> Auto-generated by [sync-agents](https://github.com/brickhouse-tech/sync-agents). Do not edit manually.",
	"> Run `sync-agents index` to regenerate.",
	"This file indexes all rules, skills, and workflows defined in `.agents/`.",
}

// generatedSections are the H2 titles the old generator owned.
var generatedSections = map[string]bool{
	"Rules": true, "Skills": true, "Workflows": true, "Agents": true,
	"Plans": true, "Specs": true, "ADRs": true, "Hooks": true, "State": true,
}

// generatedLine matches every body line the old generator could write
// in a generated section, across all versions:
//
//   - index and hook entries, with an optional OS badge and description
//   - "_No ..._" placeholders, including the retired state placeholder
//   - the State pointer sentence and the ADR preamble
//   - the Accepted, Proposed, and Shared subheadings
//   - blank lines
//
// A section with any other line holds something a human wrote and is
// kept whole.
var generatedLine = regexp.MustCompile("^(" +
	`- \[[^\]]+\]\(\.agents/[^)]+\)( ` + "`" + `\[(macos|linux|unix|windows)\]` + "`" + `)?( — .*)?` +
	`|_No .+_` +
	`|Follow \[rules/state\.md\]\(\.agents/rules/state\.md\): .*` +
	`|Architecture Decision Records\. Denied records are NOT listed here.*` +
	`|### (Accepted|Proposed|Shared)` +
	`|)$`)

// migrateAgentsMD turns an AGENTS.md written by an earlier generator
// into a user-owned file (SPEC-013 §Migration). It is pure and
// idempotent.
//
// It changes only what the old generator provably wrote. The
// claude-imports region is removed from any AGENTS.md, generated or
// not. In a file that starts with generatedHeader, the header becomes
// AgentsMDStub, and each generated section whose every body line
// matches generatedLine is removed.
//
// Everything else is kept in order, each kept block byte for byte:
// ## Inherits, ## Tools, unknown sections, any generated-titled section
// that holds a hand-written line, other sync-agents regions (opaque,
// even when they contain "## " lines), and text before the first
// section. In a generated file the blank lines between kept blocks are
// normalized to one, because they were the generator's separators.
func migrateAgentsMD(text string) (string, AgentsMDMigration) {
	var m AgentsMDMigration
	text, m.ClaudeImports = stripRegionCollapsing(text, legacyClaudeImportsRegion)

	rest, ok := cutGeneratedHeader(text)
	if !ok {
		return text, m
	}
	m.Header = true

	var out strings.Builder
	out.WriteString(AgentsMDStub)
	for _, b := range splitBlocks(rest) {
		if b.title != "" && generatedSections[b.title] {
			if b.allGenerated() {
				m.Removed = append(m.Removed, b.title)
				continue
			}
			m.Kept = append(m.Kept, b.title)
		}
		body := strings.TrimRight(strings.Join(b.lines, "\n"), "\n")
		if strings.TrimSpace(body) == "" {
			continue
		}
		out.WriteString("\n" + body + "\n")
	}
	return out.String(), m
}

// stripRegionCollapsing is stripRegion that also drops the blank line a
// region in mid-file leaves doubled, so removing a block that sat
// between two blank-separated paragraphs leaves one blank line.
func stripRegionCollapsing(text string, r ManagedRegion) (string, bool) {
	start, end, ok := r.locate(text)
	if !ok {
		return text, false
	}
	head, tail := text[:start], text[end:]
	if strings.HasSuffix(head, "\n\n") && (tail == "" || strings.HasPrefix(tail, "\n")) {
		head = head[:len(head)-1]
	}
	return head + tail, true
}

// cutGeneratedHeader reports whether text starts with generatedHeader
// (blank lines ignored) and returns what follows its last line.
func cutGeneratedHeader(text string) (string, bool) {
	rest := text
	for _, want := range generatedHeader {
		for {
			line, after, found := strings.Cut(rest, "\n")
			if strings.TrimSpace(line) == "" && found {
				rest = after
				continue
			}
			if line != want {
				return text, false
			}
			rest = after
			break
		}
	}
	return rest, true
}

// agentsMDBlock is one unit of a generated AGENTS.md body: the text
// before the first section (title ""), one "## " section, or one
// sync-agents region (title "", region true).
type agentsMDBlock struct {
	title  string
	region bool
	lines  []string
}

// allGenerated reports whether every body line of a section matches
// generatedLine.
func (b agentsMDBlock) allGenerated() bool {
	for _, l := range b.lines[1:] {
		if !generatedLine.MatchString(l) {
			return false
		}
	}
	return true
}

// splitBlocks cuts text into preamble, "## " sections, and well-formed
// sync-agents regions. A region is opaque: a "## " line inside it does
// not start a section. A start marker with no matching end marker is an
// ordinary line.
func splitBlocks(text string) []agentsMDBlock {
	lines := strings.Split(strings.TrimSuffix(text, "\n"), "\n")
	blocks := []agentsMDBlock{{}}
	cur := &blocks[0]
	open := func(b agentsMDBlock) {
		blocks = append(blocks, b)
		cur = &blocks[len(blocks)-1]
	}
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		if m := regionStartPattern.FindStringSubmatch(line); m != nil && strings.HasPrefix(line, regionMarkerPrefix) {
			end := ManagedRegion{Name: m[1]}.End()
			j := i + 1
			for j < len(lines) && lines[j] != end {
				j++
			}
			if j < len(lines) {
				open(agentsMDBlock{region: true, lines: append([]string(nil), lines[i:j+1]...)})
				open(agentsMDBlock{})
				i = j
				continue
			}
		}
		if title, ok := strings.CutPrefix(line, "## "); ok {
			open(agentsMDBlock{title: strings.TrimSpace(title), lines: []string{line}})
			continue
		}
		cur.lines = append(cur.lines, line)
	}
	return blocks
}

// errConcurrentEdit reports that a file changed between read and write.
var errConcurrentEdit = errors.New("file changed during the rewrite; rerun")

// writeIfUnchanged is compare-and-swap over writeIfChanged: it writes
// next atomically only if path still holds prev, checked once before
// writing and again just before the rename, and otherwise returns
// errConcurrentEdit. The window is not zero, but an editor save during
// sync can no longer be silently undone. It is the write path for files
// sync-agents does not own (SPEC-013 §Mounts and consent).
func writeIfUnchanged(path string, prev, next []byte) error {
	_, err := writeAtomic(path, next, func(current []byte) error {
		if !bytes.Equal(current, prev) {
			return errConcurrentEdit
		}
		return nil
	})
	return err
}

// migrateProjectAgentsMD applies migrateAgentsMD to <project>/AGENTS.md
// and logs one summary line when it changed something. It is the only
// code that writes a project AGENTS.md after `init` (SPEC-013
// §Invariants); after the first run it finds nothing to do.
//
// Order: read; compute; if changed and the backup is absent, write the
// old bytes to agentsMDBackupRel; then writeIfUnchanged. A concurrent
// edit makes the write a warned no-op, and the next run retries.
// Dry-run logs the summary and writes nothing. A missing AGENTS.md is
// not an error.
func (a *App) migrateProjectAgentsMD() (AgentsMDMigration, error) {
	path := filepath.Join(a.ProjectRoot, "AGENTS.md")
	old, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return AgentsMDMigration{}, nil
	}
	if err != nil {
		return AgentsMDMigration{}, err
	}
	next, m := migrateAgentsMD(string(old))
	if !m.Changed() {
		return m, nil
	}
	if a.DryRun {
		a.Info("[dry-run] would migrate AGENTS.md: " + m.summary())
		return m, nil
	}

	backup := filepath.Join(a.ProjectRoot, ".agents", agentsMDBackupRel)
	if _, err := os.Lstat(backup); os.IsNotExist(err) {
		if err := os.MkdirAll(filepath.Dir(backup), 0o755); err != nil {
			return m, err
		}
		if _, err := writeIfChanged(backup, old); err != nil {
			return m, fmt.Errorf("back up AGENTS.md: %w", err)
		}
	} else if err != nil {
		return m, err
	}

	if err := writeIfUnchanged(path, old, []byte(next)); err != nil {
		if errors.Is(err, errConcurrentEdit) {
			a.Warn("AGENTS.md changed while sync-agents was migrating it; left as is (rerun to migrate)")
			return AgentsMDMigration{}, nil
		}
		return m, err
	}
	a.Info("AGENTS.md: " + m.summary() + ". Backup: .agents/" + agentsMDBackupRel +
		". sync-agents will not rewrite this file again.")
	return m, nil
}

// migrateAgentsMDOrWarn runs migrateProjectAgentsMD for commands whose
// own work does not depend on it, turning a failure into a warning.
func (a *App) migrateAgentsMDOrWarn() {
	if _, err := a.migrateProjectAgentsMD(); err != nil {
		a.Warn(fmt.Sprintf("AGENTS.md migration: %v", err))
	}
}

// errInheritRemoved is what the retired `inherit` command returns.
var errInheritRemoved = errors.New("inherit was removed in SPEC-013")

// CmdInherit is the hidden stub left where `inherit` used to be. Its
// links never delivered content (no tool follows links in AGENTS.md),
// and the anchors it edited were in the generated header, which is
// gone. `## Inherits` is now ordinary text in a user-owned file.
func (a *App) CmdInherit() error {
	a.Error("`sync-agents inherit` was removed: AGENTS.md is yours now; edit ## Inherits by hand (see docs/inheritance.md)")
	return errInheritRemoved
}
