package agent

import (
	"path"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// channelFixture writes three rules (one OS-scoped) under a temp
// .agents/ and returns them as sorted entries, the shape passiveEntries
// produces.
func channelFixture(t *testing.T) []Entry {
	t.Helper()
	tree := filepath.Join(t.TempDir(), ".agents")
	brew := writeArtifact(t, tree, "rules/macos/brew.md", "Use brew.\n")
	sec := writeArtifact(t, tree, "rules/security.md", "---\ndescription: Never leak secrets\n---\nNever commit secrets.\n")
	tst := writeArtifact(t, tree, "rules/testing.md", "Write tests.\n")
	return []Entry{
		{Name: "macos/brew", Source: brew, Display: ".agents/rules/macos/brew.md"},
		{Name: "security", Source: sec, Display: ".agents/rules/security.md", Description: "Never leak secrets"},
		{Name: "testing", Source: tst, Display: ".agents/rules/testing.md"},
	}
}

// channelFixtureBody is what the fixture's three sections render to.
const channelFixtureBody = "<!-- OS: macos -->\n## macos/brew\n\nUse brew.\n\n" +
	"## security\n\nNever commit secrets.\n\n" +
	"## testing\n\nWrite tests.\n\n"

// TestChannelRender_FormatGoldens pins every format's exact bytes:
// frontmatter dialect, the AGENTS.md copy for the Codex override, the
// banner, OS headers, and one trailing newline.
func TestChannelRender_FormatGoldens(t *testing.T) {
	entries := channelFixture(t)
	agentsMD := "# AGENTS.md\n\nUse pnpm.\n\n" +
		"<!-- sync-agents:openclaw-rules:start -->\n## gateway\nbody\n<!-- sync-agents:openclaw-rules:end -->\n"

	cases := []struct {
		name   string
		format Format
		frame  Frame
		want   string
	}{
		{
			name:   "markdown",
			format: FormatMarkdown,
			frame:  Frame{Banner: localBanner},
			want:   localBanner + "\n\n" + channelFixtureBody,
		},
		{
			name:   "cursor mdc",
			format: FormatCursorMDC,
			frame:  Frame{Banner: localBanner},
			want: "---\ndescription: Shared rules from .agents/ (generated by sync-agents)\nalwaysApply: true\n---\n" +
				localBanner + "\n\n" + channelFixtureBody,
		},
		{
			name:   "copilot instructions",
			format: FormatCopilotInstructions,
			frame:  Frame{Banner: globalBanner},
			want:   "---\napplyTo: \"**\"\n---\n" + globalBanner + "\n\n" + channelFixtureBody,
		},
		{
			name:   "codex override strips regions from the AGENTS.md copy",
			format: FormatCodexOverride,
			frame:  Frame{Banner: localBanner, AgentsMD: []byte(agentsMD)},
			want: "# AGENTS.md\n\nUse pnpm.\n\n" + codexOverrideNote + "\n" +
				localBanner + "\n\n" + channelFixtureBody,
		},
		{
			name:   "codex override without AGENTS.md has no copy and no note",
			format: FormatCodexOverride,
			frame:  Frame{Banner: localBanner},
			want:   localBanner + "\n\n" + channelFixtureBody,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r, err := renderChannel(tc.format, entries, tc.frame, Budget{})
			if err != nil {
				t.Fatalf("renderChannel: %v", err)
			}
			if got := string(r.Bytes); got != tc.want {
				t.Errorf("bytes mismatch\n--- got ---\n%s\n--- want ---\n%s", got, tc.want)
			}
			if want := []string{"macos/brew", "security", "testing"}; !reflect.DeepEqual(r.Inlined, want) || r.Pointers != nil {
				t.Errorf("inlined=%v pointers=%v, want all inlined", r.Inlined, r.Pointers)
			}
		})
	}
}

// TestChannelRender_EmptyEntries renders a header-only file, so a tree
// whose last rule was deleted empties the channel instead of keeping
// stale content.
func TestChannelRender_EmptyEntries(t *testing.T) {
	r, err := renderChannel(FormatMarkdown, nil, Frame{Banner: localBanner}, Budget{})
	if err != nil {
		t.Fatalf("renderChannel: %v", err)
	}
	if got, want := string(r.Bytes), localBanner+"\n\n"; got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

// TestChannelRender_Deterministic guards status's byte comparison:
// rendering the same input twice yields the same bytes.
func TestChannelRender_Deterministic(t *testing.T) {
	entries := channelFixture(t)
	b := Budget{Cap: Cap{Limit: 120, Unit: CapUTF16}}
	first, err := renderChannel(FormatCursorMDC, entries, Frame{Banner: localBanner}, b)
	if err != nil {
		t.Fatalf("renderChannel: %v", err)
	}
	second, err := renderChannel(FormatCursorMDC, entries, Frame{Banner: localBanner}, b)
	if err != nil {
		t.Fatalf("renderChannel: %v", err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Errorf("two renders differ:\n%q\n%q", first.Bytes, second.Bytes)
	}
}

// TestChannelRender_MissingSourceFails reports a vanished source rather
// than rendering a partial bundle.
func TestChannelRender_MissingSourceFails(t *testing.T) {
	entries := []Entry{{Name: "gone", Source: filepath.Join(t.TempDir(), "gone.md"), Display: ".agents/rules/gone.md"}}
	if _, err := renderChannel(FormatMarkdown, entries, Frame{Banner: localBanner}, Budget{}); err == nil {
		t.Fatal("expected an error for a missing source")
	}
}

// TestChannelStripAllRegions removes every writer's region but leaves an
// unterminated start marker as text.
func TestChannelStripAllRegions(t *testing.T) {
	in := "top\n\n" +
		"<!-- sync-agents:a:start -->\nA\n<!-- sync-agents:a:end -->\n\n" +
		"middle\n\n" +
		"<!-- sync-agents:b:start -->\nB\n<!-- sync-agents:b:end -->\n\n" +
		"<!-- sync-agents:c:start -->\ndangling\n"
	want := "top\n\nmiddle\n\n<!-- sync-agents:c:start -->\ndangling\n"
	if got := stripAllRegions(in); got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

// TestMount_ConsentTruthTable is SPEC-013 §Mounts and consent row by
// row, for each mount kind.
func TestMount_ConsentTruthTable(t *testing.T) {
	link := LinkMount{At: NativePath{AnchorBase, "x"}}
	region := RegionMount{Host: NativePath{AnchorHome, "AGENTS.md"}, Region: CodexRulesRegion, CreateHost: true}
	ownedRegion := RegionMount{Host: NativePath{AnchorHome, "AGENTS.md"}, Region: OpenClawRulesRegion}
	config := ConfigListMount{File: NativePath{AnchorBase, "opencode.json"}, Key: "instructions"}

	cases := []struct {
		name  string
		mount Mount
		facts MountFacts
		ok    bool
		why   string
	}{
		{"ours already there refreshes even without home or consent", ownedRegion,
			MountFacts{Scope: ScopeGlobal, NativeExists: true, CarriesOurs: true}, true, ""},
		{"global, home missing", link, MountFacts{Scope: ScopeGlobal}, false, whyNotInstalled},
		{"global, home missing, explicit", link, MountFacts{Scope: ScopeGlobal, Explicit: true}, true, ""},
		{"local ignores the home gate", link, MountFacts{Scope: ScopeLocal}, true, ""},
		{"link never needs consent over an existing path", link,
			MountFacts{Scope: ScopeGlobal, HomeExists: true, NativeExists: true}, true, ""},
		{"region host owned by the tool, missing", ownedRegion,
			MountFacts{Scope: ScopeGlobal, HomeExists: true}, false, whyHostOwned},
		{"region host owned by the tool, missing, explicit", ownedRegion,
			MountFacts{Scope: ScopeGlobal, HomeExists: true, Explicit: true}, false, whyHostOwned},
		{"region host we may create, missing", region,
			MountFacts{Scope: ScopeGlobal, HomeExists: true}, true, ""},
		{"region host exists without consent", region,
			MountFacts{Scope: ScopeGlobal, HomeExists: true, NativeExists: true}, false, whyNeedsConsent},
		{"region host exists with consent", region,
			MountFacts{Scope: ScopeGlobal, HomeExists: true, NativeExists: true, Explicit: true}, true, ""},
		{"owned region host exists without consent", ownedRegion,
			MountFacts{Scope: ScopeGlobal, HomeExists: true, NativeExists: true}, false, whyNeedsConsent},
		{"config absent is created", config, MountFacts{Scope: ScopeLocal}, true, ""},
		{"config exists without consent", config,
			MountFacts{Scope: ScopeLocal, NativeExists: true}, false, whyNeedsConsent},
		{"config exists with consent", config,
			MountFacts{Scope: ScopeLocal, NativeExists: true, Explicit: true}, true, ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ok, why := mayMount(tc.mount, tc.facts)
			if ok != tc.ok || why != tc.why {
				t.Errorf("mayMount = (%v, %q), want (%v, %q)", ok, why, tc.ok, tc.why)
			}
		})
	}
}

// TestChannelSpecs_Invariants checks the SPEC-013 §Invariants that the
// delivery table itself must satisfy.
func TestChannelSpecs_Invariants(t *testing.T) {
	t.Run("every row is a registered tool at a scope it has", func(t *testing.T) {
		for id, rows := range channelSpecs {
			tool, ok := ResolveTool(id)
			if !ok || tool.ID != id {
				t.Errorf("%q is not a canonical tool ID", id)
				continue
			}
			for scope := range rows {
				if !tool.HasScope(scope) {
					t.Errorf("%s has a %s row but no %s scope", id, scope, scope)
				}
			}
		}
	})

	t.Run("openclaw has no local channel", func(t *testing.T) {
		if _, ok := channelSpecs["openclaw"][ScopeLocal]; ok {
			t.Error("openclaw is global-only (SPEC-012)")
		}
	})

	t.Run("index file names are unique per scope", func(t *testing.T) {
		for _, scope := range []Scope{ScopeLocal, ScopeGlobal} {
			seen := map[string]string{}
			for id, rows := range channelSpecs {
				spec, ok := rows[scope]
				if !ok {
					continue
				}
				name := spec.Format.IndexName(id)
				if other, dup := seen[name]; dup {
					t.Errorf("%s: %s and %s both write %s", scope, id, other, name)
				}
				seen[name] = id
			}
		}
	})

	t.Run("one writer per region", func(t *testing.T) {
		seen := map[string]string{}
		for id, rows := range channelSpecs {
			for scope, spec := range rows {
				rm, ok := spec.Mount.(RegionMount)
				if !ok {
					continue
				}
				owner := id + "/" + scope.String()
				if other, dup := seen[rm.Region.Name]; dup {
					t.Errorf("region %s has two writers: %s and %s", rm.Region.Name, owner, other)
				}
				seen[rm.Region.Name] = owner
			}
		}
	})

	t.Run("no native path is a Claude read path", func(t *testing.T) {
		// Claude loads .claude/** and CLAUDE.md / CLAUDE.local.md
		// anywhere, and AGENTS.md in the project directory. Region
		// hosts named AGENTS.md inside another tool's home (Codex,
		// the OpenClaw workspace) are read by Claude only in a session
		// started there (SPEC-013 T9).
		for id, rows := range channelSpecs {
			for scope, spec := range rows {
				np := nativePathOf(spec.Mount)
				base := path.Base(np.Rel)
				if strings.HasPrefix(np.Rel, ".claude/") || base == "CLAUDE.md" || base == "CLAUDE.local.md" {
					t.Errorf("%s/%s delivers into Claude's path %s", id, scope, np.Rel)
				}
				if np.Under == AnchorBase && np.Rel == "AGENTS.md" {
					t.Errorf("%s/%s delivers into the project AGENTS.md", id, scope)
				}
			}
		}
	})

	t.Run("MergeGlobal only at local scope", func(t *testing.T) {
		for id, rows := range channelSpecs {
			if rows[ScopeGlobal].MergeGlobal {
				t.Errorf("%s: a global channel cannot merge global entries", id)
			}
		}
	})

	t.Run("gaps and channels do not overlap", func(t *testing.T) {
		for id, rows := range channelGaps {
			for scope := range rows {
				if _, ok := channelSpecs[id][scope]; ok {
					t.Errorf("%s/%s is both a channel and a gap", id, scope)
				}
			}
		}
	})
}

// nativePathOf returns the path a mount places or edits.
func nativePathOf(m Mount) NativePath {
	switch m := m.(type) {
	case LinkMount:
		return m.At
	case RegionMount:
		return m.Host
	case ConfigListMount:
		return m.File
	}
	return NativePath{}
}

// TestChannelPassiveEntries_Selection keeps passive rules, workflows,
// and skills; drops invocable ones and every other bucket; reports a
// broken frontmatter without stopping; and fills Display, Description,
// and OnDemand.
func TestChannelPassiveEntries_Selection(t *testing.T) {
	tree := filepath.Join(t.TempDir(), ".agents")
	writeArtifact(t, tree, "config", "os = linux\n")
	writeArtifact(t, tree, "rules/style.md", "---\ndescription: House style\ntrigger: model_decision\n---\nBody.\n")
	writeArtifact(t, tree, "rules/deploy.md", "---\ninvocable: true\n---\nDeploy.\n")
	writeArtifact(t, tree, "rules/broken.md", "---\ninvocable: maybe\n---\nBody.\n")
	writeArtifact(t, tree, "workflows/release.md", "Release.\n")
	writeArtifact(t, tree, "workflows/standup.md", "---\ninvocable: false\n---\nStandup.\n")
	writeArtifact(t, tree, "skills/pdf/SKILL.md", "Read PDFs.\n")
	writeArtifact(t, tree, "skills/tone/SKILL.md", "---\ninvocable: false\n---\nTone.\n")
	writeArtifact(t, tree, "agents/reviewer.md", "---\ninvocable: false\n---\nReview.\n")
	writeArtifact(t, tree, "plans/p.md", "Plan.\n")
	writeArtifact(t, tree, "index/codex.md", "generated\n")

	arts, err := discoverChannelArtifacts(tree, false)
	if err != nil {
		t.Fatalf("discover: %v", err)
	}
	entries, errs := passiveEntries(arts, ".agents")
	if len(errs) != 1 || !strings.Contains(errs[0].Error(), "broken.md") {
		t.Errorf("errs = %v, want one error naming broken.md", errs)
	}
	want := []Entry{
		{Name: "standup", Source: filepath.Join(tree, "workflows/standup.md"), Display: ".agents/workflows/standup.md"},
		{Name: "style", Source: filepath.Join(tree, "rules/style.md"), Display: ".agents/rules/style.md", Description: "House style", OnDemand: true},
		{Name: "tone", Source: filepath.Join(tree, "skills/tone/SKILL.md"), Display: ".agents/skills/tone/SKILL.md"},
	}
	if !reflect.DeepEqual(entries, want) {
		t.Errorf("entries:\n got %+v\nwant %+v", entries, want)
	}
}

// TestChannelPassiveEntries_OSGating delivers only this machine's OS
// scope under index = local, and every scope (still name-sorted) for a
// committed index.
func TestChannelPassiveEntries_OSGating(t *testing.T) {
	tree := filepath.Join(t.TempDir(), ".agents")
	writeArtifact(t, tree, "config", "os = linux\n")
	writeArtifact(t, tree, "rules/base.md", "Base.\n")
	writeArtifact(t, tree, "rules/linux/apt.md", "Apt.\n")
	writeArtifact(t, tree, "rules/macos/brew.md", "Brew.\n")
	writeArtifact(t, tree, "rules/windows/winget.md", "Winget.\n")

	names := func(allOS bool) []string {
		arts, err := discoverChannelArtifacts(tree, allOS)
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		entries, errs := passiveEntries(arts, "~/.agents")
		if len(errs) != 0 {
			t.Fatalf("errs: %v", errs)
		}
		var out []string
		for _, e := range entries {
			out = append(out, e.Name+"="+e.Display)
		}
		return out
	}
	if got, want := names(false), []string{"base=~/.agents/rules/base.md", "linux/apt=~/.agents/rules/linux/apt.md"}; !reflect.DeepEqual(got, want) {
		t.Errorf("host OS only: got %v, want %v", got, want)
	}
	want := []string{
		"base=~/.agents/rules/base.md",
		"linux/apt=~/.agents/rules/linux/apt.md",
		"macos/brew=~/.agents/rules/macos/brew.md",
		"windows/winget=~/.agents/rules/windows/winget.md",
	}
	if got := names(true); !reflect.DeepEqual(got, want) {
		t.Errorf("all OS: got %v, want %v", got, want)
	}
}

// TestChannelMergeEntries lets a project entry override the global entry
// of the same name and keeps the result sorted.
func TestChannelMergeEntries(t *testing.T) {
	project := []Entry{{Name: "b", Display: ".agents/rules/b.md"}, {Name: "d", Display: ".agents/rules/d.md"}}
	global := []Entry{{Name: "a", Display: "~/.agents/rules/a.md"}, {Name: "b", Display: "~/.agents/rules/b.md"}, {Name: "c", Display: "~/.agents/rules/c.md"}}
	got := mergeEntries(project, global)
	want := []Entry{
		{Name: "a", Display: "~/.agents/rules/a.md"},
		{Name: "b", Display: ".agents/rules/b.md"},
		{Name: "c", Display: "~/.agents/rules/c.md"},
		{Name: "d", Display: ".agents/rules/d.md"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %+v, want %+v", got, want)
	}
}

// TestChannelIndexName uses the extension each tool reads.
func TestChannelIndexName(t *testing.T) {
	if got := FormatCursorMDC.IndexName("cursor"); got != "cursor.mdc" {
		t.Errorf("cursor: %s", got)
	}
	if got := FormatCopilotInstructions.IndexName("copilot"); got != "copilot.md" {
		t.Errorf("copilot: %s", got)
	}
}

// TestChannelBudgetSourcesResolve calls every row's BudgetSource with an
// empty environment, so a row cannot reference a resolver that fails on
// a machine without the tool's config.
func TestChannelBudgetSourcesResolve(t *testing.T) {
	tc := ToolContext{Parent: "/home/u", Home: "/home/u/.codex", Env: mapEnv(nil, nil)}
	for id, rows := range channelSpecs {
		for scope, spec := range rows {
			if spec.Budget == nil {
				continue
			}
			b, err := spec.Budget(tc)
			if err != nil {
				t.Errorf("%s/%s: %v", id, scope, err)
			}
			if b.Cap.Limit <= 0 {
				t.Errorf("%s/%s: limit %d", id, scope, b.Cap.Limit)
			}
		}
	}
}
