package agent

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ConcatBanner is prepended to every regenerated concat file. The
// "Do not edit" line is what tells future agents (and humans) to
// modify the source artifacts under ~/.agents/, not the generated
// concat output.
//
// The banner is a Markdown comment so it doesn't render as visible
// noise when Codeium/Copilot/Codex load the file.
const ConcatBanner = `<!--
Generated by sync-agents — do not edit by hand.
Source: ~/.agents/  (rules/, skills/, workflows/)
Regenerated on each ` + "`sync-agents global sync`" + `.
-->

`

// ConcatEntry is one artifact's contribution to a concat target. The
// orchestration layer collects these per concat-Path, sorts them by
// Name, and RegenerateConcat writes them as a single file.
type ConcatEntry struct {
	// Name is the artifact's identifier — also the heading text in
	// the generated concat. Must be unique within a concat target;
	// duplicate names would produce duplicate `## name` headings
	// and confuse downstream tooling.
	Name string

	// SourcePath is the absolute path to the artifact's content file
	// under ~/.agents/. For rules and workflows, the .md file
	// itself; for skills, the SKILL.md inside the dir.
	SourcePath string

	// Summary renders the entry as a one-line description plus
	// SourcePath instead of its body. Only region fitting sets it, to
	// keep a region under its host's size cap.
	Summary bool
}

// RegenerateConcat writes a concat file at concatPath whose content
// is the banner followed by each entry as a `## <name>` heading and
// the artifact body, alphabetized by name.
//
// Atomicity: the file is written via tmp + rename. If anything in
// the regeneration fails (read, build, write), the destination is
// either the original file (unchanged) or non-existent if it didn't
// exist before. Partial state never reaches the destination.
//
// Idempotency: if the regenerated content byte-equals the existing
// destination, RegenerateConcat does not perform the rename. This
// preserves the destination's mtime so SPEC-002's "no writes on
// re-run" idempotency contract holds at the stat level.
//
// Returns (changed, error): changed=true means the file was written
// (new content or new file); changed=false means the file already
// had the correct content. Errors short-circuit; callers should
// log the error and continue with other concat targets.
//
// Frontmatter handling: the source artifact's YAML frontmatter is
// stripped before inclusion. The reason is that frontmatter is
// sync-agents metadata, not content the destination tool should see.
// The artifact body — what comes after the closing `---\n` — is
// what gets appended.
func RegenerateConcat(concatPath string, entries []ConcatEntry) (bool, error) {
	body, err := buildEntriesBody(entries)
	if err != nil {
		return false, err
	}
	// Concat files often live a few levels deep
	// (e.g. ~/.codeium/windsurf/memories/).
	if err := os.MkdirAll(filepath.Dir(concatPath), 0o755); err != nil {
		return false, err
	}
	return writeIfChanged(concatPath, append([]byte(ConcatBanner), body...))
}

// buildEntriesBody renders entries as `## <name>` sections sorted by
// name, each followed by the artifact body with frontmatter stripped.
// It is the single builder behind every concat-shaped output (whole
// concat files, spliced regions, and the status comparisons of both),
// so what status expects can never drift from what sync writes.
func buildEntriesBody(entries []ConcatEntry) ([]byte, error) {
	// Sort by Name so the output is deterministic regardless of how
	// the orchestration layer discovered the entries.
	sorted := make([]ConcatEntry, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	var buf bytes.Buffer
	for _, e := range sorted {
		body, err := readArtifactBody(e.SourcePath)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", e.SourcePath, err)
		}
		// SPEC-006: an OS-scoped artifact ("macos/brew") gets a header
		// comment so a reader of the flat concat knows which platform
		// the block targets. Invisible when the tool renders Markdown.
		if scope, _, ok := strings.Cut(e.Name, "/"); ok && isOSScopeDir(scope) {
			fmt.Fprintf(&buf, "<!-- OS: %s -->\n", scope)
		}
		fmt.Fprintf(&buf, "## %s\n\n", e.Name)
		if e.Summary {
			fmt.Fprintf(&buf, "%s\nFull text, read it when relevant: %s\n\n", entrySummary(e.SourcePath, body), e.SourcePath)
			continue
		}
		buf.Write(body)
		// Always end an entry on a blank line so the next heading
		// starts cleanly. We trim the body's trailing whitespace
		// first to avoid stacking blank lines if the source already
		// ended with one.
		if !bytes.HasSuffix(bytes.TrimRight(buf.Bytes(), " \t"), []byte("\n")) {
			buf.WriteByte('\n')
		}
		buf.WriteByte('\n')
	}
	return buf.Bytes(), nil
}

// readArtifactBody returns the body of an artifact file with any
// leading YAML frontmatter stripped.
//
// Detection: a file begins with `---\n` or `---\r\n`, and the
// frontmatter ends at the next `---` on its own line. Anything after
// the closing delimiter is the body. Files without frontmatter
// return their full content.
//
// The body's leading blank lines are trimmed so concat output doesn't
// stack empty lines after the heading. Trailing whitespace is
// preserved.
func readArtifactBody(path string) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if !bytes.HasPrefix(raw, []byte("---\n")) && !bytes.HasPrefix(raw, []byte("---\r\n")) {
		return raw, nil
	}

	text := string(raw)
	if strings.HasPrefix(text, "---\r\n") {
		text = text[5:]
	} else {
		text = text[4:]
	}

	endIdx := indexFrontmatterEnd(text)
	if endIdx == -1 {
		// No closing delimiter — treat the whole file as content
		// rather than swallowing it silently. The concat will look
		// a bit odd but the user can see why.
		return raw, nil
	}

	// Skip the closing `---` line itself.
	afterClose := text[endIdx:]
	if i := strings.IndexByte(afterClose, '\n'); i != -1 {
		afterClose = afterClose[i+1:]
	} else {
		afterClose = ""
	}

	body := strings.TrimLeft(afterClose, "\n\r ")
	return []byte(body), nil
}

// entrySummary is the one-line stand-in for an entry body: the
// frontmatter description when the file declares one, else the first
// paragraph after the title.
func entrySummary(path string, body []byte) string {
	if d := artifactDescription(path); d != "" {
		return d
	}
	var para []string
	for _, line := range strings.Split(string(body), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "<!--") {
			if len(para) > 0 {
				break
			}
			continue
		}
		para = append(para, line)
	}
	if len(para) == 0 {
		return "(no summary)"
	}
	const maxSummary = 140
	text := strings.Join(para, " ")
	if len(text) > maxSummary {
		text = truncateAtWord(text, maxSummary) + "…"
	}
	return text
}
