package agent

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ConcatBanner is prepended to every regenerated concat file. The
// "Do not edit" line is what tells future agents (and humans) to
// modify the source artifacts under ~/.agents/, not the generated
// concat output.
//
// The banner is a Markdown comment so it doesn't render as visible
// noise when Codeium/Copilot/Codex load the file.
const ConcatBanner = `<!--
Generated by sync-agents — do not edit by hand.
Source: ~/.agents/  (rules/, skills/, workflows/)
Regenerated on each ` + "`sync-agents global sync`" + `.
-->

`

// ConcatEntry is one artifact's contribution to a concat target. The
// orchestration layer collects these per concat-Path, sorts them by
// Name, and RegenerateConcat writes them as a single file.
type ConcatEntry struct {
	// Name is the artifact's identifier — also the heading text in
	// the generated concat. Must be unique within a concat target;
	// duplicate names would produce duplicate `## name` headings
	// and confuse downstream tooling.
	Name string

	// SourcePath is the absolute path to the artifact's content file
	// under ~/.agents/. For rules and workflows, the .md file
	// itself; for skills, the SKILL.md inside the dir.
	SourcePath string
}

// RegenerateConcat writes a concat file at concatPath whose content
// is the banner followed by each entry as a `## <name>` heading and
// the artifact body, alphabetized by name.
//
// Atomicity: the file is written via tmp + rename. If anything in
// the regeneration fails (read, build, write), the destination is
// either the original file (unchanged) or non-existent if it didn't
// exist before. Partial state never reaches the destination.
//
// Idempotency: if the regenerated content byte-equals the existing
// destination, RegenerateConcat does not perform the rename. This
// preserves the destination's mtime so SPEC-002's "no writes on
// re-run" idempotency contract holds at the stat level.
//
// Returns (changed, error): changed=true means the file was written
// (new content or new file); changed=false means the file already
// had the correct content. Errors short-circuit; callers should
// log the error and continue with other concat targets.
//
// Frontmatter handling: the source artifact's YAML frontmatter is
// stripped before inclusion. The reason is that frontmatter is
// sync-agents metadata, not content the destination tool should see.
// The artifact body — what comes after the closing `---\n` — is
// what gets appended.
func RegenerateConcat(concatPath string, entries []ConcatEntry) (bool, error) {
	// Sort by Name so the output is deterministic regardless of how
	// the orchestration layer discovered the entries.
	sorted := make([]ConcatEntry, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	// Build the new content in memory. Concat files are small (a
	// handful of rules at most), so this is fine.
	var buf bytes.Buffer
	buf.WriteString(ConcatBanner)
	for _, e := range sorted {
		body, err := readArtifactBody(e.SourcePath)
		if err != nil {
			return false, fmt.Errorf("read %s: %w", e.SourcePath, err)
		}
		fmt.Fprintf(&buf, "## %s\n\n", e.Name)
		buf.Write(body)
		// Always end an entry on a blank line so the next heading
		// starts cleanly. We trim the body's trailing whitespace
		// first to avoid stacking blank lines if the source already
		// ended with one.
		if !bytes.HasSuffix(bytes.TrimRight(buf.Bytes(), " \t"), []byte("\n")) {
			buf.WriteByte('\n')
		}
		buf.WriteByte('\n')
	}

	newContent := buf.Bytes()

	// If existing content matches new content, skip the write to
	// preserve mtime.
	if existing, err := os.ReadFile(concatPath); err == nil {
		if bytes.Equal(existing, newContent) {
			return false, nil
		}
	}

	// Ensure the destination directory exists. Concat files often
	// live a few levels deep (e.g. ~/.codeium/windsurf/memories/).
	if err := os.MkdirAll(filepath.Dir(concatPath), 0o755); err != nil {
		return false, err
	}

	// Atomic write: tmp file in the same directory, then rename.
	// Same directory is important so the rename stays on one
	// filesystem (cross-filesystem rename falls back to copy+delete
	// on some platforms and loses atomicity).
	tmp, err := os.CreateTemp(filepath.Dir(concatPath), filepath.Base(concatPath)+".tmp-*")
	if err != nil {
		return false, err
	}
	tmpName := tmp.Name()
	// Clean up the tmp file on any error path. If we successfully
	// rename it, the deferred Remove is a no-op (file no longer
	// exists at tmpName).
	defer os.Remove(tmpName)

	if _, err := tmp.Write(newContent); err != nil {
		tmp.Close()
		return false, err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return false, err
	}
	if err := tmp.Close(); err != nil {
		return false, err
	}

	if err := os.Rename(tmpName, concatPath); err != nil {
		return false, err
	}
	return true, nil
}

// readArtifactBody returns the body of an artifact file with any
// leading YAML frontmatter stripped.
//
// Detection: a file begins with `---\n` or `---\r\n`, and the
// frontmatter ends at the next `---` on its own line. Anything after
// the closing delimiter is the body. Files without frontmatter
// return their full content.
//
// The body's leading blank lines are trimmed so concat output doesn't
// stack empty lines after the heading. Trailing whitespace is
// preserved.
func readArtifactBody(path string) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if !bytes.HasPrefix(raw, []byte("---\n")) && !bytes.HasPrefix(raw, []byte("---\r\n")) {
		return raw, nil
	}

	text := string(raw)
	if strings.HasPrefix(text, "---\r\n") {
		text = text[5:]
	} else {
		text = text[4:]
	}

	endIdx := indexFrontmatterEnd(text)
	if endIdx == -1 {
		// No closing delimiter — treat the whole file as content
		// rather than swallowing it silently. The concat will look
		// a bit odd but the user can see why.
		return raw, nil
	}

	// Skip the closing `---` line itself.
	afterClose := text[endIdx:]
	if i := strings.IndexByte(afterClose, '\n'); i != -1 {
		afterClose = afterClose[i+1:]
	} else {
		afterClose = ""
	}

	body := strings.TrimLeft(afterClose, "\n\r ")
	return []byte(body), nil
}
