package agent

import (
	"bytes"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

// deliverAgentsMD is a user-owned AGENTS.md: no generated header, so
// the migration leaves it alone and no command may change its bytes.
const deliverAgentsMD = "# AGENTS.md\n\nUse pnpm, not npm.\n"

// allChannelTargets is every local target, Claude and Windsurf (fold)
// plus the four channel tools.
var allChannelTargets = []string{"claude", "windsurf", "cursor", "copilot", "codex", "opencode"}

// newDeliverApp builds a project with two rules and a skill, a
// user-owned AGENTS.md, and a separate global root holding one rule of
// its own and one the project overrides. The global root's parent
// stands in for $HOME (Codex budget lookups stay inside it).
func newDeliverApp(t *testing.T, targets ...string) (*App, string, *bytes.Buffer) {
	t.Helper()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "AGENTS.md"), deliverAgentsMD)
	writeFile(t, filepath.Join(root, ".agents", "rules", "security.md"), "---\ndescription: Never leak secrets\n---\nNever commit secrets.\n")
	writeFile(t, filepath.Join(root, ".agents", "rules", "testing.md"), "Write tests.\n")
	writeFile(t, filepath.Join(root, ".agents", "skills", "deploy", "SKILL.md"), "---\nname: deploy\ndescription: Deploy it\n---\nRun deploy.\n")
	global := filepath.Join(t.TempDir(), ".agents")
	writeFile(t, filepath.Join(global, "rules", "global-only.md"), "Global rule.\n")
	writeFile(t, filepath.Join(global, "rules", "security.md"), "Global security, overridden.\n")
	var buf bytes.Buffer
	app := &App{
		ProjectRoot:   root,
		GlobalRoot:    global,
		ActiveTargets: targets,
		Stdout:        &buf,
		Stderr:        &buf,
	}
	return app, root, &buf
}

// The exact bytes of each index file for newDeliverApp's tree.
const (
	deliverRules = "## security\n\nNever commit secrets.\n\n## testing\n\nWrite tests.\n\n"

	wantCursorIndex = "---\ndescription: Shared rules from .agents/ (generated by sync-agents)\nalwaysApply: true\n---\n" +
		localBanner + "\n\n" +
		"## global-only\n\nGlobal rule.\n\n" + deliverRules

	wantCopilotIndex = "---\napplyTo: \"**\"\n---\n" + localBanner + "\n\n" + deliverRules

	wantCodexIndex = "# AGENTS.md\n\nUse pnpm, not npm.\n\n" + codexOverrideNote + "\n" +
		localBanner + "\n\n" + deliverRules

	wantOpencodeIndex = localBanner + "\n\n" + deliverRules

	wantOpencodeJSON = "{\n  \"instructions\": [\".agents/index/opencode.md\"]\n}\n"
)

// treeSnapshot maps every path under root (except .git) to its
// content, or "-> target" for a symlink, or "/" for a directory.
func treeSnapshot(t *testing.T, root string) map[string]string {
	t.Helper()
	snap := map[string]string{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, p)
		if rel == "." {
			return nil
		}
		if rel == ".git" {
			return filepath.SkipDir
		}
		switch {
		case d.Type()&fs.ModeSymlink != 0:
			target, _ := os.Readlink(p)
			snap[rel] = "-> " + target
		case d.IsDir():
			snap[rel] = "/"
		default:
			data, _ := os.ReadFile(p)
			snap[rel] = string(data)
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return snap
}

// links returns every symlink under root outside .agents/, as
// path -> link text.
func links(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	for p, v := range treeSnapshot(t, root) {
		if strings.HasPrefix(v, "-> ") && !strings.HasPrefix(p, ".agents"+string(filepath.Separator)) {
			out[filepath.ToSlash(p)] = strings.TrimPrefix(v, "-> ")
		}
	}
	return out
}

// TestDeliver_EveryTargetLinkSetAndIndexBytes pins the whole local
// layout SPEC-013 §Usage promises for every target: the exact set of
// links sync places, the bytes of each index file, the created
// opencode.json, and the .gitignore lines.
func TestDeliver_EveryTargetLinkSetAndIndexBytes(t *testing.T) {
	app, root, buf := newDeliverApp(t, allChannelTargets...)
	if err := app.CmdSync(); err != nil {
		t.Fatalf("CmdSync: %v\n%s", err, buf)
	}

	wantLinks := map[string]string{
		".claude/rules":                 "../.agents/rules",
		".claude/skills":                "../.agents/skills",
		".windsurf/rules":               "../.agents/rules",
		".windsurf/skills":              "../.agents/skills",
		".cursor/skills":                "../.agents/skills",
		".github/copilot/skills":        "../../.agents/skills",
		".codex/skills":                 "../.agents/skills",
		".opencode/skills":              "../.agents/skills",
		".cursor/rules/sync-agents.mdc": "../../.agents/index/cursor.mdc",
		".github/instructions/sync-agents.instructions.md": "../../.agents/index/copilot.md",
		"AGENTS.override.md":                               ".agents/index/codex.md",
	}
	if got := links(t, root); !reflect.DeepEqual(got, wantLinks) {
		t.Errorf("links:\n got %v\nwant %v", got, wantLinks)
	}

	assertContent(t, filepath.Join(root, ".agents", "index", "cursor.mdc"), wantCursorIndex)
	assertContent(t, filepath.Join(root, ".agents", "index", "copilot.md"), wantCopilotIndex)
	assertContent(t, filepath.Join(root, ".agents", "index", "codex.md"), wantCodexIndex)
	assertContent(t, filepath.Join(root, ".agents", "index", "opencode.md"), wantOpencodeIndex)
	assertContent(t, filepath.Join(root, "opencode.json"), wantOpencodeJSON)
	assertContent(t, filepath.Join(root, "AGENTS.md"), deliverAgentsMD)

	gi, _ := os.ReadFile(filepath.Join(root, ".gitignore"))
	for _, line := range []string{".agents/index/", ".cursor/rules/sync-agents.mdc",
		".github/instructions/sync-agents.instructions.md", "AGENTS.override.md"} {
		if !containsExactLine(string(gi), line) {
			t.Errorf(".gitignore lacks %q:\n%s", line, gi)
		}
	}
	if containsExactLine(string(gi), "opencode.json") {
		t.Error("opencode.json is a config, not a link; it must not be gitignored")
	}
}

// TestDeliver_SecondSyncWritesNothing: a converged project is a no-op.
// Every file keeps its mtime and sync reports nothing it changed.
func TestDeliver_SecondSyncWritesNothing(t *testing.T) {
	app, root, buf := newDeliverApp(t, allChannelTargets...)
	if err := app.CmdSync(); err != nil {
		t.Fatalf("first sync: %v\n%s", err, buf)
	}
	mtimes := func() map[string]time.Time {
		m := map[string]time.Time{}
		filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
			if fi, err := os.Lstat(p); err == nil {
				m[p] = fi.ModTime()
			}
			return nil
		})
		return m
	}
	before := mtimes()
	buf.Reset()
	if err := app.CmdSync(); err != nil {
		t.Fatalf("second sync: %v\n%s", err, buf)
	}
	if after := mtimes(); !reflect.DeepEqual(before, after) {
		for p, ts := range after {
			if !before[p].Equal(ts) {
				t.Errorf("second sync touched %s", p)
			}
		}
	}
	for _, noise := range []string{"Regenerated", "Linked:", "Repaired:", "Created", "Added"} {
		if strings.Contains(buf.String(), noise) {
			t.Errorf("second sync reported %q:\n%s", noise, buf)
		}
	}
}

// TestDeliver_CleanRestoresPreSyncTree: clean removes every link, the
// index, the created opencode.json, and the directories they needed.
// .gitignore lines are kept, as they always were.
func TestDeliver_CleanRestoresPreSyncTree(t *testing.T) {
	app, root, buf := newDeliverApp(t, allChannelTargets...)
	before := treeSnapshot(t, root)
	if err := app.CmdSync(); err != nil {
		t.Fatalf("CmdSync: %v\n%s", err, buf)
	}
	if err := app.CmdClean(); err != nil {
		t.Fatalf("CmdClean: %v\n%s", err, buf)
	}
	after := treeSnapshot(t, root)
	delete(after, ".gitignore")
	if !reflect.DeepEqual(before, after) {
		var diff []string
		for p, v := range after {
			if before[p] != v {
				diff = append(diff, "+ "+p)
			}
		}
		for p := range before {
			if _, ok := after[p]; !ok {
				diff = append(diff, "- "+p)
			}
		}
		sort.Strings(diff)
		t.Errorf("clean left the tree changed:\n%s\n%s", strings.Join(diff, "\n"), buf)
	}
}

// TestDeliver_UserAgentsMDByteIdentical: sync, index, and the refresh
// add/adr/watch run never write a user-owned AGENTS.md (SPEC-013
// §Invariants), even though Codex's override copies it.
func TestDeliver_UserAgentsMDByteIdentical(t *testing.T) {
	app, root, buf := newDeliverApp(t, allChannelTargets...)
	path := filepath.Join(root, "AGENTS.md")
	fiBefore, _ := os.Stat(path)
	steps := map[string]func() error{
		"sync":    app.CmdSync,
		"index":   app.CmdIndex,
		"refresh": func() error { app.refreshIndex(); return nil },
	}
	for _, name := range []string{"sync", "index", "refresh"} {
		if err := steps[name](); err != nil {
			t.Fatalf("%s: %v\n%s", name, err, buf)
		}
		assertContent(t, path, deliverAgentsMD)
	}
	if fi, _ := os.Stat(path); !fi.ModTime().Equal(fiBefore.ModTime()) {
		t.Error("AGENTS.md mtime changed")
	}
}

// TestDeliver_IndexRefreshCreatesNothingInToolDirs: `index` (and add,
// watch) write only .agents/index/; mounts are sync's job.
func TestDeliver_IndexRefreshCreatesNothingInToolDirs(t *testing.T) {
	app, root, buf := newDeliverApp(t, allChannelTargets...)
	if err := app.CmdIndex(); err != nil {
		t.Fatalf("CmdIndex: %v\n%s", err, buf)
	}
	assertContent(t, filepath.Join(root, ".agents", "index", "copilot.md"), wantCopilotIndex)
	for _, p := range []string{".cursor", ".github", "AGENTS.override.md", "opencode.json"} {
		assertAbsent(t, filepath.Join(root, p))
	}
}

// TestDeliver_CodexOverrideFollowsAgentsMD: an AGENTS.md edit makes
// the codex channel stale until the next index, which rewrites the
// copy.
func TestDeliver_CodexOverrideFollowsAgentsMD(t *testing.T) {
	app, root, buf := newDeliverApp(t, "codex")
	if err := app.CmdSync(); err != nil {
		t.Fatalf("CmdSync: %v\n%s", err, buf)
	}
	writeFile(t, filepath.Join(root, "AGENTS.md"), "# AGENTS.md\n\nUse bun.\n")
	rows, err := app.channelRows(ScopeLocal, nil)
	if err != nil || len(rows) != 1 || rows[0].State != string(ChannelStale) {
		t.Fatalf("rows = %+v, %v; want one stale codex row", rows, err)
	}
	if err := app.CmdIndex(); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(filepath.Join(root, "AGENTS.override.md"))
	if !strings.HasPrefix(string(data), "# AGENTS.md\n\nUse bun.\n") {
		t.Errorf("override does not carry the edited AGENTS.md:\n%s", data)
	}
}

// TestDeliver_StatusRows: synced after sync, stale after a rule edit,
// unmounted before sync.
func TestDeliver_StatusRows(t *testing.T) {
	app, root, buf := newDeliverApp(t, "cursor", "copilot")
	states := func() []string {
		rows, err := app.channelRows(ScopeLocal, nil)
		if err != nil {
			t.Fatal(err)
		}
		var s []string
		for _, r := range rows {
			s = append(s, r.Tool+"="+r.State)
		}
		return s
	}
	if got := states(); !reflect.DeepEqual(got, []string{"cursor=stale", "copilot=stale"}) {
		t.Errorf("before sync: %v", got)
	}
	if err := app.CmdSync(); err != nil {
		t.Fatalf("CmdSync: %v\n%s", err, buf)
	}
	if got := states(); !reflect.DeepEqual(got, []string{"cursor=synced", "copilot=synced"}) {
		t.Errorf("after sync: %v", got)
	}
	writeFile(t, filepath.Join(root, ".agents", "rules", "testing.md"), "Write more tests.\n")
	if got := states(); !reflect.DeepEqual(got, []string{"cursor=stale", "copilot=stale"}) {
		t.Errorf("after edit: %v", got)
	}
	if err := app.CmdIndex(); err != nil {
		t.Fatal(err)
	}
	os.Remove(filepath.Join(root, ".cursor", "rules", "sync-agents.mdc"))
	if got := states(); !reflect.DeepEqual(got, []string{"cursor=unmounted", "copilot=synced"}) {
		t.Errorf("after removing the cursor link: %v", got)
	}
}

// TestDeliver_StatusMigrateRow: status flags an AGENTS.md that still
// carries the old generated index.
func TestDeliver_StatusMigrateRow(t *testing.T) {
	app, root, buf := newDeliverApp(t, "claude")
	writeFile(t, filepath.Join(root, "AGENTS.md"), strings.Join(generatedHeader, "\n")+"\n\n## Rules\n\n- [security](.agents/rules/security.md)\n")
	if err := app.CmdStatus(); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "[migrate] AGENTS.md still has the generated index") {
		t.Errorf("no migrate row:\n%s", buf)
	}
}

// TestDeliver_OpencodeConsent: an existing opencode.json is the
// user's. Config targets do not edit it; one --targets run does, and
// later runs keep the entry.
func TestDeliver_OpencodeConsent(t *testing.T) {
	app, root, buf := newDeliverApp(t, "opencode")
	cfg := filepath.Join(root, "opencode.json")
	const mine = "{\n  \"$schema\": \"https://opencode.ai/config.json\"\n}\n"
	writeFile(t, cfg, mine)

	res, err := app.deliverChannels(ChannelRun{Scope: ScopeLocal, Mode: ChannelMount})
	if err != nil || len(res) != 1 || res[0].State != ChannelUnmounted {
		t.Fatalf("without consent: %+v %v", res, err)
	}
	if !strings.Contains(res[0].Detail, "--targets opencode") {
		t.Errorf("detail does not name the consent command: %q", res[0].Detail)
	}
	assertContent(t, cfg, mine)

	app.TargetsFromFlag = true
	res, err = app.deliverChannels(ChannelRun{Scope: ScopeLocal, Mode: ChannelMount, Explicit: app.explicitTargets()})
	if err != nil || res[0].State != ChannelSynced {
		t.Fatalf("with consent: %+v %v\n%s", res, err, buf)
	}
	assertContent(t, cfg, "{\n  \"$schema\": \"https://opencode.ai/config.json\",\n  \"instructions\": [\".agents/index/opencode.md\"]\n}\n")

	app.TargetsFromFlag = false
	res, _ = app.deliverChannels(ChannelRun{Scope: ScopeLocal, Mode: ChannelMount})
	if res[0].State != ChannelSynced {
		t.Errorf("an entry that carries ours must stay synced: %+v", res)
	}

	if _, err := app.cleanChannels(ScopeLocal, nil); err != nil {
		t.Fatal(err)
	}
	assertContent(t, cfg, mine)
}

// TestDeliver_OpencodeJSONCIsManual: a config with comments is never
// rewritten; the row names the entry to add by hand.
func TestDeliver_OpencodeJSONCIsManual(t *testing.T) {
	app, root, _ := newDeliverApp(t, "opencode")
	cfg := filepath.Join(root, "opencode.json")
	const jsonc = "{\n  // mine\n  \"model\": \"x\"\n}\n"
	writeFile(t, cfg, jsonc)
	res, err := app.deliverChannels(ChannelRun{Scope: ScopeLocal, Mode: ChannelMount, Explicit: []string{"opencode"}})
	if err != nil || res[0].State != ChannelManual || !strings.Contains(res[0].Detail, `".agents/index/opencode.md"`) {
		t.Fatalf("got %+v %v", res, err)
	}
	assertContent(t, cfg, jsonc)
}

// TestDeliver_RealOverrideIsConflict: a user's own AGENTS.override.md
// is never clobbered or gitignored, and sync exits non-zero.
func TestDeliver_RealOverrideIsConflict(t *testing.T) {
	app, root, buf := newDeliverApp(t, "codex")
	writeFile(t, filepath.Join(root, "AGENTS.override.md"), "mine\n")
	if err := app.CmdSync(); err == nil {
		t.Fatalf("sync must report the conflict\n%s", buf)
	}
	assertContent(t, filepath.Join(root, "AGENTS.override.md"), "mine\n")
	gi, _ := os.ReadFile(filepath.Join(root, ".gitignore"))
	if containsExactLine(string(gi), "AGENTS.override.md") {
		t.Error("a user's real AGENTS.override.md must not be gitignored")
	}
}

// TestDeliver_LegacyPlacementsRemoved: the old fold links into
// .agents/rules go, the .mdc link lands in a real .cursor/rules (not
// through the old fold into .agents/rules), drilled per-rule links go
// while the user's own files stay, and a foreign symlink stays.
func TestDeliver_LegacyPlacementsRemoved(t *testing.T) {
	app, root, buf := newDeliverApp(t, "cursor", "copilot", "codex")
	mustLink := func(target, link string) {
		os.MkdirAll(filepath.Dir(link), 0o755)
		if err := os.Symlink(target, link); err != nil {
			t.Fatal(err)
		}
	}
	mustLink("../.agents/rules", filepath.Join(root, ".cursor", "rules"))
	mustLink("../.agents/rules", filepath.Join(root, ".codex", "rules"))
	writeFile(t, filepath.Join(root, ".github", "copilot", "rules", "team.md"), "team")
	mustLink("../../../.agents/rules/security.md", filepath.Join(root, ".github", "copilot", "rules", "security.md"))
	foreign := t.TempDir()
	mustLink(foreign, filepath.Join(root, ".opencode", "rules"))

	if err := app.CmdSync(); err != nil {
		t.Fatalf("CmdSync: %v\n%s", err, buf)
	}
	assertRealDir(t, filepath.Join(root, ".cursor", "rules"))
	assertResolvesTo(t, filepath.Join(root, ".cursor", "rules", "sync-agents.mdc"), filepath.Join(root, ".agents", "index", "cursor.mdc"))
	assertAbsent(t, filepath.Join(root, ".agents", "rules", "sync-agents.mdc"))
	assertAbsent(t, filepath.Join(root, ".codex", "rules"))
	assertAbsent(t, filepath.Join(root, ".github", "copilot", "rules", "security.md"))
	assertContent(t, filepath.Join(root, ".github", "copilot", "rules", "team.md"), "team")
	if fi, err := os.Lstat(filepath.Join(root, ".opencode", "rules")); err != nil || fi.Mode()&os.ModeSymlink == 0 {
		t.Error("a symlink outside .agents/ must be left alone")
	}
}

// TestDeliver_LegacyFoldDryRunPlansTheLink: under --dry-run the old
// fold is still on disk; the plan must not report it as a conflict.
func TestDeliver_LegacyFoldDryRunPlansTheLink(t *testing.T) {
	app, root, buf := newDeliverApp(t, "cursor")
	os.MkdirAll(filepath.Join(root, ".cursor"), 0o755)
	os.Symlink("../.agents/rules", filepath.Join(root, ".cursor", "rules"))
	app.DryRun = true
	if err := app.CmdSync(); err != nil {
		t.Fatalf("dry-run sync: %v\n%s", err, buf)
	}
	if !strings.Contains(buf.String(), "would link: "+filepath.Join(root, ".cursor", "rules", "sync-agents.mdc")) {
		t.Errorf("dry-run does not plan the .mdc link:\n%s", buf)
	}
	assertResolvesTo(t, filepath.Join(root, ".cursor", "rules"), filepath.Join(root, ".agents", "rules"))
	assertAbsent(t, filepath.Join(root, ".agents", "index"))
}

// TestDeliver_SameTreeSkipsGlobalChannelTools: when the project is
// $HOME, Copilot, Codex, and opencode are global sync's; Cursor keeps
// its local channel and merges nothing (the trees are the same).
func TestDeliver_SameTreeSkipsGlobalChannelTools(t *testing.T) {
	home := t.TempDir()
	writeFile(t, filepath.Join(home, ".agents", "rules", "r.md"), "Rule.\n")
	var buf bytes.Buffer
	app := &App{ProjectRoot: home, GlobalRoot: filepath.Join(home, ".agents"),
		ActiveTargets: []string{"cursor", "copilot", "codex", "opencode"}, Stdout: &buf, Stderr: &buf}
	res, err := app.deliverChannels(ChannelRun{Scope: ScopeLocal, Mode: ChannelMount})
	if err != nil {
		t.Fatal(err)
	}
	if len(res) != 1 || res[0].Channel.Tool != "cursor" {
		t.Fatalf("bound %+v, want cursor only", res)
	}
	for _, p := range []string{".github", "AGENTS.override.md", "opencode.json"} {
		assertAbsent(t, filepath.Join(home, p))
	}
	if n := strings.Count(string(res[0].Rendered.Bytes), "## r\n"); n != 1 {
		t.Errorf("rule rendered %d times, want once", n)
	}
}

// TestDeliver_IndexCommitNeverMergesGlobal: a committed cursor.mdc
// must not carry one developer's global rules, and nothing is
// gitignored.
func TestDeliver_IndexCommitNeverMergesGlobal(t *testing.T) {
	app, root, buf := newDeliverApp(t, "cursor")
	writeFile(t, filepath.Join(root, ".agents", "config"), "index = commit\n")
	if err := app.CmdSync(); err != nil {
		t.Fatalf("CmdSync: %v\n%s", err, buf)
	}
	data, _ := os.ReadFile(filepath.Join(root, ".agents", "index", "cursor.mdc"))
	if strings.Contains(string(data), "global-only") {
		t.Error("committed index carries a global rule")
	}
	gi, _ := os.ReadFile(filepath.Join(root, ".gitignore"))
	if containsExactLine(string(gi), ".agents/index/") || containsExactLine(string(gi), ".cursor/rules/sync-agents.mdc") {
		t.Errorf("index = commit must not ignore the index or its links:\n%s", gi)
	}
}

func TestGitignoreEntries(t *testing.T) {
	root := "/p"
	link := ChannelResult{State: ChannelSynced, Channel: Channel{Spec: channelSpecs["cursor"][ScopeLocal], Native: "/p/.cursor/rules/sync-agents.mdc"}}
	conflict := ChannelResult{State: ChannelConflict, Channel: Channel{Spec: channelSpecs["codex"][ScopeLocal], Native: "/p/AGENTS.override.md"}}
	config := ChannelResult{State: ChannelSynced, Channel: Channel{Spec: channelSpecs["opencode"][ScopeLocal], Native: "/p/opencode.json"}}
	ours := ClaudeMDDecision{Current: ClaudeMDOurLink}
	cases := []struct {
		name   string
		policy IndexPolicy
		res    []ChannelResult
		claude ClaudeMDDecision
		want   []string
	}{
		{"local", IndexLocal, []ChannelResult{link, conflict, config}, ClaudeMDDecision{}, []string{".agents/index/", ".cursor/rules/sync-agents.mdc"}},
		{"local with our CLAUDE.md", IndexLocal, []ChannelResult{link}, ours, []string{".agents/index/", ".cursor/rules/sync-agents.mdc", "CLAUDE.md"}},
		{"commit", IndexCommit, []ChannelResult{link, config}, ours, []string{"CLAUDE.md"}},
		{"no channels", IndexLocal, nil, ClaudeMDDecision{}, nil},
	}
	for _, c := range cases {
		if got := gitignoreEntries(c.policy, root, c.res, c.claude); !reflect.DeepEqual(got, c.want) {
			t.Errorf("%s: got %v want %v", c.name, got, c.want)
		}
	}
}

func TestLinksBucket(t *testing.T) {
	rules, _ := BucketForDir("rules")
	skills, _ := BucketForDir("skills")
	cases := []struct {
		target string
		b      Bucket
		want   bool
	}{
		{"claude", rules, true},
		{"windsurf", rules, true},
		{"wave", rules, true},
		{"cursor", rules, false},
		{"copilot", rules, false},
		{"codex", rules, false},
		{"opencode", rules, false},
		{"cursor", skills, true},
	}
	for _, c := range cases {
		if got := linksBucket(c.target, c.b); got != c.want {
			t.Errorf("linksBucket(%s, %s) = %v", c.target, c.b.Dir, got)
		}
	}
}

func TestReadConfigIndex(t *testing.T) {
	dir := t.TempDir()
	if p, err := ReadConfigIndex(dir); p != IndexLocal || err != nil {
		t.Errorf("absent config: %v %v", p, err)
	}
	for val, want := range map[string]IndexPolicy{"commit": IndexCommit, "local": IndexLocal, "COMMIT": IndexCommit} {
		writeFile(t, filepath.Join(dir, "config"), "# index = commit\nindex = "+val+"\n")
		if p, err := ReadConfigIndex(dir); p != want || err != nil {
			t.Errorf("%s: %v %v", val, p, err)
		}
	}
	writeFile(t, filepath.Join(dir, "config"), "index = maybe\n")
	if p, err := ReadConfigIndex(dir); p != IndexLocal || err == nil {
		t.Errorf("typo must fall back to local with an error: %v %v", p, err)
	}
}

// TestCmdHook_ReplacesOldBlock: re-running the hook command upgrades
// the pre-SPEC-013 block in place and keeps the user's lines; a third
// run changes nothing.
func TestCmdHook_ReplacesOldBlock(t *testing.T) {
	root := t.TempDir()
	hook := filepath.Join(root, ".git", "hooks", "pre-commit")
	old := "#!/bin/sh\necho before\n\n# --- sync-agents start ---\nif command -v sync-agents >/dev/null 2>&1; then\n" +
		"  sync-agents sync 2>/dev/null\n  sync-agents index 2>/dev/null\n" +
		"  git add AGENTS.md CLAUDE.md .claude/ .windsurf/ .cursor/ .github/copilot/ 2>/dev/null || true\nfi\n" +
		"# --- sync-agents end ---\necho after\n"
	writeFile(t, hook, old)
	var buf bytes.Buffer
	app := &App{ProjectRoot: root, Stdout: &buf, Stderr: &buf}
	if err := app.CmdHook(); err != nil {
		t.Fatal(err)
	}
	want := "#!/bin/sh\necho before\n\n" + hookBlock + "echo after\n"
	assertContent(t, hook, want)
	if err := app.CmdHook(); err != nil {
		t.Fatal(err)
	}
	assertContent(t, hook, want)
	if !strings.Contains(buf.String(), "already installed") {
		t.Errorf("second run should be a no-op:\n%s", buf.String())
	}
	if strings.Contains(want, "AGENTS.md") || strings.Contains(want, "CLAUDE.md") {
		t.Error("the hook must not git-add files that may not exist")
	}
}
