package agent

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// This file removes the placements earlier versions made and SPEC-013
// retires (§Migration, step 4), at project and at global scope. Each
// removal needs a proof that the path is sync-agents'; anything else is
// reported and left.

// legacyFold is one tool-directory link the pre-SPEC-013 sync made:
// Path folded (or drilled) Source, the bucket directory in .agents/.
type legacyFold struct {
	Path, Source string
}

// legacyFoldPaths lists the folds linksBucket now withholds: every
// <tool dir>/<bucket> fold of a passive bucket into a tool that has a
// local channel (.cursor/rules, .github/copilot/rules, .codex/rules,
// .opencode/rules). It is derived from the same registry linksBucket
// reads, so the two cannot disagree.
func legacyFoldPaths(root string) []legacyFold {
	var folds []legacyFold
	for _, tool := range Tools {
		for _, b := range Buckets {
			if b.SyncsToTool(tool.ID) && !linksBucket(tool.ID, b) {
				folds = append(folds, legacyFold{
					Path:   filepath.Join(ResolveTargetDir(tool.ID, root), b.Dir),
					Source: filepath.Join(root, ".agents", b.Dir),
				})
			}
		}
	}
	sort.Slice(folds, func(i, j int) bool { return folds[i].Path < folds[j].Path })
	return folds
}

// removeLegacyPlacements removes the local legacy links (SPEC-013
// §Migration, step 4) and returns the paths it removed. The proof is
// the link itself: a symlink that resolves into the folded bucket
// (.agents/rules) is sync-agents' (the old fold). A real directory
// there is the tool's own: only the links inside it that resolve into
// the bucket (the old per-rule drill) are removed, and the directory
// goes only when that leaves it empty. Our own channel link in
// .cursor/rules points into .agents/index/, so it is never taken for a
// legacy one. Anything else is reported and left. It is idempotent and
// dry-run aware.
func (a *App) removeLegacyPlacements() []string {
	var removed []string
	for _, fold := range legacyFoldPaths(a.ProjectRoot) {
		path, tree := fold.Path, fold.Source
		fi, err := os.Lstat(path)
		if err != nil {
			continue
		}
		switch {
		case fi.Mode()&os.ModeSymlink != 0:
			if !pointsInto(path, tree) {
				a.Info(fmt.Sprintf("left %s: a symlink outside %s is not sync-agents'", a.display(path), a.display(tree)))
				continue
			}
			if a.removePath(path) {
				removed = append(removed, path)
				a.pruneEmptyParents(filepath.Dir(path), a.ProjectRoot)
			}
		case fi.IsDir():
			entries, err := os.ReadDir(path)
			if err != nil {
				a.Warn(fmt.Sprintf("read %s: %v", a.display(path), err))
				continue
			}
			for _, e := range entries {
				p := filepath.Join(path, e.Name())
				if e.Type()&os.ModeSymlink != 0 && pointsInto(p, tree) && a.removePath(p) {
					removed = append(removed, p)
				}
			}
			a.pruneEmptyParents(path, a.ProjectRoot)
		default:
			a.Info(fmt.Sprintf("left %s: a real file is not sync-agents'", a.display(path)))
		}
	}
	if len(removed) > 0 && !a.DryRun {
		a.Info("Removed legacy rule links: rules now reach Cursor, Copilot, Codex, and opencode through .agents/index/")
	}
	return removed
}

// pointsInto reports whether the symlink at link resolves inside dir.
// A dangling link is judged by its text, so a fold whose target was
// deleted is still recognized.
func pointsInto(link, dir string) bool {
	within := func(p, root string) bool {
		return p == root || strings.HasPrefix(p, root+string(filepath.Separator))
	}
	if real, err := filepath.EvalSymlinks(link); err == nil {
		if rdir, err := filepath.EvalSymlinks(dir); err == nil && within(real, rdir) {
			return true
		}
	}
	text, err := os.Readlink(link)
	if err != nil {
		return false
	}
	if !filepath.IsAbs(text) {
		text = filepath.Join(filepath.Dir(link), text)
	}
	return within(filepath.Clean(text), filepath.Clean(dir))
}

// legacyConcatBanner opens the whole-file concat outputs SPEC-013
// retires: ~/.github/copilot/instructions.md, ~/.codex/instructions.md,
// and the old ~/.codeium/windsurf/memories/global_rules.md. A file that
// starts with it was written entirely by sync-agents.
const legacyConcatBanner = "<!--\nGenerated by sync-agents"

// isLegacyConcat reports whether data is one of those files.
func isLegacyConcat(data []byte) bool {
	return bytes.HasPrefix(data, []byte(legacyConcatBanner))
}

// legacyProof is what proves a legacy global path is sync-agents' to
// remove.
type legacyProof int

const (
	// proofConcatBanner: a regular file that starts with
	// legacyConcatBanner.
	proofConcatBanner legacyProof = iota

	// proofLinksIntoTree: symlinks that resolve into the global root,
	// at the path or anywhere below it. Everything else stays, and so
	// does a directory that still holds anything.
	proofLinksIntoTree
)

// globalLegacyPlacements lists the dead global paths earlier versions
// wrote (SPEC-013 §Migration, step 4), relative to the global root's
// parent, by the tool whose run cleans them. Each is removed only when
// its proof holds. The old global_rules.md is not listed: the codeium
// channel rewrites it in place as its region. ~/.claude/CLAUDE.md's
// import block is stripped by global sync itself.
var globalLegacyPlacements = []struct {
	Tool  string
	Rel   string
	Proof legacyProof
}{
	{"copilot", ".github/copilot/instructions.md", proofConcatBanner}, // a path Copilot never read
	{"codex", ".codex/instructions.md", proofConcatBanner},            // a path Codex never read
	{"cursor", ".cursor/rules", proofLinksIntoTree},                   // per-rule .md links; Cursor reads only .mdc
}

// removeGlobalLegacyPlacements removes the legacy global paths of the
// run's tools whose proof holds and returns what it removed. A file
// at one of those paths without the proof is reported and left. It is
// idempotent and dry-run aware. Directories the removals leave empty
// are pruned up to, never including, the global root's parent.
func (a *App) removeGlobalLegacyPlacements(tools []Tool) []string {
	parent := a.ResolveGlobalRootParent()
	root := a.ResolveGlobalRoot()
	active := map[string]bool{}
	for _, t := range tools {
		active[t.ID] = true
	}
	var removed []string
	for _, p := range globalLegacyPlacements {
		if !active[p.Tool] {
			continue
		}
		path := filepath.Join(parent, filepath.FromSlash(p.Rel))
		switch p.Proof {
		case proofConcatBanner:
			removed = append(removed, a.removeLegacyConcat(path, parent)...)
		case proofLinksIntoTree:
			removed = append(removed, a.removeLinksInto(path, root, parent)...)
		}
	}
	if len(removed) > 0 && !a.DryRun {
		a.Info(fmt.Sprintf("Removed %d legacy global file(s) no tool reads: rules now reach Copilot, Codex, and Cursor through their channels", len(removed)))
	}
	return removed
}

// removeLegacyConcat removes the regular file at path when it starts
// with legacyConcatBanner, and reports any other file there.
func (a *App) removeLegacyConcat(path, stop string) []string {
	fi, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		a.Warn(fmt.Sprintf("inspect %s: %v", a.display(path), err))
		return nil
	}
	if !fi.Mode().IsRegular() {
		a.Info(fmt.Sprintf("left %s: not a regular file, so not sync-agents'", a.display(path)))
		return nil
	}
	head, err := readHead(path, len(legacyConcatBanner))
	if err != nil {
		a.Warn(fmt.Sprintf("read %s: %v", a.display(path), err))
		return nil
	}
	if !isLegacyConcat(head) {
		a.Info(fmt.Sprintf("left %s: it does not start with the sync-agents banner, so it is yours", a.display(path)))
		return nil
	}
	if !a.removePath(path) {
		return nil
	}
	a.pruneEmptyParents(filepath.Dir(path), stop)
	return []string{path}
}

// readHead returns up to n bytes from the start of path.
func readHead(path string, n int) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	buf := make([]byte, n)
	m, err := io.ReadFull(f, buf)
	if err != nil && !errors.Is(err, io.ErrUnexpectedEOF) && !errors.Is(err, io.EOF) {
		return nil, err
	}
	return buf[:m], nil
}

// removeLinksInto removes every symlink at or under path that resolves
// into tree, then prunes the directories that leaves empty. Real files
// and links elsewhere are the user's and stay.
func (a *App) removeLinksInto(path, tree, stop string) []string {
	if _, err := os.Lstat(path); os.IsNotExist(err) {
		return nil
	}
	var removed []string
	err := filepath.WalkDir(path, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.Type()&os.ModeSymlink != 0 && pointsInto(p, tree) && a.removePath(p) {
			removed = append(removed, p)
		}
		return nil
	})
	if err != nil {
		a.Warn(fmt.Sprintf("walk %s: %v", a.display(path), err))
	}
	for i := len(removed) - 1; i >= 0; i-- {
		a.pruneEmptyParents(filepath.Dir(removed[i]), stop)
	}
	return removed
}
